### PR TITLE
bootstrap peer dependency

### PR DESCRIPTION
**Pull request by tsm91**
3.4.5 does not exist, can't install it via npm

### CODE REVIEW

**Comment by tsm91** [comment]
haha, apparently the button `commit and create a pull request` didn't work as i thought, i created a pull request for my fork xd

was the first time i didn't cloned the repo and did everything on github

**Comment by stefanocudini** [comment]
tnk!

**Comment by tsm91** [comment]
@stefanocudini don't forget to publish the new version to npm

**Comment by stefanocudini** [comment]
done!

**Comment by tsm91** [comment]
hmm, not seem to be updated. Also did an `npm cache clean`.

**Pull request merged**
